spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/ExerciseDB
    password: Mario[1996]cotumaccio!
  jpa:
    show_sql: true
    database: mysql
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 5050
